app = "packaging-catalog-web"
primary_region = "ams"

[build]
  dockerfile = "apps/web/Dockerfile"
  [build.args]
    NEXT_PUBLIC_API_BASE = "https://packaging-catalog-api.fly.dev" # or your custom domain

[env]
  PORT = "3000"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_BASE = "https://packaging-catalog-api.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443