app = "packaging-catalog-admin"
primary_region = "fra"

[build]
dockerfile = "Dockerfile"
target = "runtime-nextjs"

[build.args]
APP_NAME = "admin"
NEXT_PUBLIC_API_BASE = "https://packaging-catalog-api.fly.dev"

[env]
NODE_ENV = "production"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
