app = "packaging-catalog-api"
primary_region = "ams"

[build]
  dockerfile = "apps/api/Dockerfile"

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

# Run Prisma migrations before a release becomes active
[deploy]
  release_command = "pnpm prisma migrate deploy"

# Health check (assuming /health returns 200)
[[services]]
  internal_port = 3001
  protocol = "tcp"

  [services.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443