name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: catalog
        ports: [ '5432:5432' ]
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s
          --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'pnpm' }
      - run: corepack enable
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm i
      - run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/catalog" > apps/api/.env
      - run: pnpm -F @pkg/db migrate:dev --name ci --create-only || true
      - run: pnpm -F @pkg/db generate
      - run: pnpm -r build || true
      - run: pnpm -r lint
